export const DASHBOARD_ROLES = ["super_admin", "admin", "operator", "viewer"] as const;

export type DashboardUserRole = (typeof DASHBOARD_ROLES)[number];

export const PERMISSIONS = {
  STAFF_MANAGE: "staff.manage",
  USERS_MANAGE: "users.manage",
  USERS_READ: "users.read",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_READ: "settings.read",
  AUDIT_VIEW: "audit.view",
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_MANAGE: "products.manage",
  PRODUCTS_READ: "products.read",
  PRODUCTS_WRITE: "products.write",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  ORDERS_VIEW: "orders.view",
  ORDERS_MANAGE: "orders.manage",
  POS_CREATE_SALE: "pos.create_sale",
  REPORTS_VIEW: "reports.view",
  FILES_READ: "files.read",
  FILES_MANAGE: "files.manage",
  API_KEYS_READ: "api_keys.read",
  API_KEYS_MANAGE: "api_keys.manage",
  STOCK_MOVEMENTS_READ: "stock_movements.read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<DashboardUserRole, Permission[]> = {
  super_admin: [
    PERMISSIONS.STAFF_MANAGE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.POS_CREATE_SALE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.FILES_READ,
    PERMISSIONS.FILES_MANAGE,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.API_KEYS_MANAGE,
    PERMISSIONS.STOCK_MOVEMENTS_READ,
  ],
  admin: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_MANAGE,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.PRODUCTS_WRITE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.FILES_READ,
    PERMISSIONS.FILES_MANAGE,
    PERMISSIONS.API_KEYS_READ,
    PERMISSIONS.SETTINGS_READ,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.STOCK_MOVEMENTS_READ,
  ],
  operator: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_MANAGE,
    PERMISSIONS.FILES_READ,
    PERMISSIONS.STOCK_MOVEMENTS_READ,
  ],
  viewer: [
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_READ,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.STOCK_MOVEMENTS_READ,
  ],
};

export function hasPermission(role: DashboardUserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}
